URL_SERVICE = "https://9936aed0-f926-428c-b78c-8d60b8de0087.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
CREATE_KIT_PATH = "/api/v1/kits/"
